version: '3.8'

services:
  ecommerce-mmr:
    build: ecommerce-mmr
    mem_limit: 512m
    ports:
      - "8080:8080"
    environment:
      DB_URL: jdbc:mysql://ecommerce_mmr:3306/db_dawi_ecommerce_mmr?createDatabaseIfNotExist=true&serverTimezone=UTC     
      DB_USER: root
      DB_PASSWORD: admin
    restart: always
    depends_on:
      ecommerce_mmr:
          condition: service_healthy
  ecommerce_mmr:
    image: mysql:8.3.0 
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_PASSWORD: admin
      MYSQL_DATABASE: db_dawi_ecommerce_mmr
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 10s
      retries: 10